// Auto-generated by skills/project-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/overview/": [
    {
      "text": "项目地图",
      "items": [],
    },
  ],
  "/architecture/": [
    {
      "text": "架构设计",
      "items": [],
    },
  ],
  "/concepts/": [
    {
      "text": "核心概念",
      "items": [],
    },
  ],
  "/modules/": [
    {
      "text": "核心模块",
      "items": [],
    },
  ],
  "/dataflow/": [
    {
      "text": "数据流",
      "items": [],
    },
  ],
  "/operations/": [
    {
      "text": "工程运维",
      "items": [],
    },
  ],
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX",
  },
];
