// Auto-generated by skills/org-to-vitepress/scripts/regenerate-vitepress-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {};

export const wikiNav = [
  { text: "首页", link: "/INDEX" }
];
