// Auto-generated by skills/project-wiki/scripts/regenerate-sidebar.mjs
// Do not edit by hand; re-run the script after adding or renaming docs.

// @ts-nocheck

export const wikiSidebar = {
  "/": [
    {
      "text": "项目地图",
      "items": [],
      "collapsed": false,
    },
    {
      "text": "架构设计",
      "items": [],
      "collapsed": false,
    },
    {
      "text": "核心概念",
      "items": [],
      "collapsed": false,
    },
    {
      "text": "核心模块",
      "items": [],
      "collapsed": false,
    },
    {
      "text": "数据流",
      "items": [],
      "collapsed": false,
    },
    {
      "text": "工程运维",
      "items": [],
      "collapsed": false,
    },
  ],
};

export const wikiNav = [
  {
    "text": "首页",
    "link": "/INDEX",
  },
];
